
import sys
import os
import unittest
from unittest.mock import MagicMock
from pathlib import Path

# Add project root to path
sys.path.append(str(Path(__file__).parent.parent))

# Mock dependencies that might be missing in the test environment
sys.modules["yt_dlp"] = MagicMock()
sys.modules["yt_dlp.utils"] = MagicMock()
sys.modules["requests"] = MagicMock()
sys.modules["dotenv"] = MagicMock()

# Mock config to avoid import errors or side effects
sys.modules["config"] = MagicMock()

# Now import the module under test
from utils.animated_captions import generate_animated_ass

class TestAnimatedCaptions(unittest.TestCase):
    def setUp(self):
        self.output_path = "test_output.ass"
        self.settings = {
            "font": "Arial",
            "font_size": 20,
            "outline_width": 1,
            "shadow_depth": 1,
            "margin_bottom": 10,
            "words_per_line": 5,
            "highlight_color": "&H00FFFF",
            "style": "animated"
        }

    def tearDown(self):
        if os.path.exists(self.output_path):
            os.remove(self.output_path)

    def test_ass_injection_prevention(self):
        """Test that special characters in text are replaced to prevent ASS injection."""
        segments = [
            {
                "start": 0.0,
                "end": 2.0,
                "text": "Hello {injection} \\ world"
            }
        ]

        generate_animated_ass(segments, self.output_path, self.settings)

        with open(self.output_path, "r", encoding="utf-8") as f:
            content = f.read()

        # Check that original special characters are NOT present
        self.assertNotIn("{injection}", content, "Opening curly brace not escaped")
        # Backslash might be used in ASS tags (e.g. \c, \fscx), so checking for raw backslash
        # surrounded by spaces (from the input " \ ") or just checking for the replacement.
        # The input " \ " should become " ＼ "

        # Check for the sanitized versions
        self.assertIn("Hello ｛injection｝ ＼ world", content.replace("{\\c&H00FFFF\\fscx120\\fscy120}", "").replace("{\\c&H00FFFFFF\\fscx100\\fscy100}", "").replace("Dialogue: ", ""))

        # More robust check: check raw content for the replacement characters
        self.assertIn("｛", content)
        self.assertIn("｝", content)
        self.assertIn("＼", content)

        # Check that ASS tags are still valid (start with { and end with })
        # We can regex check that all { in the file are followed by valid ASS commands
        import re
        # This regex matches { followed by something that is NOT a full-width brace
        # But our sanitization replaces content braces. The structural braces for tags should remain.
        # Since we only replaced content, the structural tags generated by the code like {\c...} should be fine.

        # Let's ensure we didn't break the file structure
        self.assertIn("[Script Info]", content)
        self.assertIn("[Events]", content)

if __name__ == "__main__":
    unittest.main()
